name: Build & Release Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Ensure local.properties with flutter.sdk
        run: |
          echo "FLUTTER_ROOT env is: "
          echo "flutter.sdk=" > android/local.properties
          echo "--- local.properties before build ---"
          cat android/local.properties

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Verbose
        run: |
          echo "--- local.properties right before flutter build apk ---"
          cat android/local.properties
          flutter build apk --release -v

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
